### ISSUE TITLE
Python binding example

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#100]
One of the major advantage of Protobuf etc seems to be readily available language bindings for Python and other languages. I'm wondering how difficult would it be to call rpclib service from Python client. Any example would be great (especially demonstrating bit complex type like vector of some objects).

**Comment by sztomi** [comment]
gRPC (which uses protobuf) is not simply a library, like rpclib. gRPC is a set of libraries and code generators for various languages. So in that sense, rpclib does not offer a solution, since it's only a C++ library. But it implements an open and simple protocol: msgpack-rpc. Several implementations exist for a variety of languages, making it easy to connect. Check out [mprpc](https://github.com/studio-ousia/mprpc), which I used in the early iterations of rpclib to make sure that the protocol is implemented correctly.

If the response or parameter contains something that is translatable to a vector, msgpack will serialize/deserialize that easily. For example:

Python server:

```python
from gevent.server import StreamServer
from mprpc import RPCServer

class SumServer(RPCServer):
    def get_numbers(self):
        return [2, 3, 4, 5]

server = StreamServer(('127.0.0.1', 6000), SumServer())
server.serve_forever()
```

rpclib client:

```cpp
rpc::client c("localhost", 6000);
auto numbers = c.call("get_numbers").as<std::vector<int>>();
```

**Comment by sztomi** [comment]
@sytelus does this answer your question?

**Comment by sztomi** [comment]
@sytelus Closing this, let me know if you have further questions.
