### ISSUE TITLE
Visual Studio 2013 support

### ISSUE THREAD

**Issue by sztomi** [rpclib/rpclib#110]
With #33 (C++11 support) merged, a good extension to supported compilers is MSVC 2013. It has some C++11 support, but a few crucial things are missing:

  * `thread_local`: can be emulated with TLS or FLS (FLS is only supported from Vista, but it's much nicer)
  * `constexpr`: since only constexpr variables are used, consts or macros will solve it

`boost::thread_specific_ptr` *could be* required as a sort of "shim" library and it would also help with older xcode support (instead of manually implementing it).

**Comment by mbr0wn** [comment]
I would argue the value of `constexpr` is minimal as long as we don't `constexpr` variables in template expansions or we use `constexpr` functions. It seems like you're suggesting to just replace them with `const` -- I think that's probably fine.

**Comment by moguorong** [comment]
I don't know how to migrate to Visual Studio 2015, using cmake3.8 and using Visual Studio 2015 to compile a lot of errors that I can't solve

Compiling for 32-bit
CMake Warning (dev) at CMakeLists.txt:136 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:248 (set_rpclib_flags)
This warning is for project developers.  Use -Wno-dev to suppress it.

MSVC -> forcing use of statically-linked runtime.
CMake Warning (dev) at cmake/localbuild/Findrpclib.cmake:31 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  examples/echo/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/localbuild/Findrpclib.cmake:31 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  examples/mandelbrot/CMakeLists.txt:5 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find SFML (missing:  SFML_GRAPHICS_LIBRARY SFML_WINDOW_LIBRARY SFML_SYSTEM_LIBRARY)
CMake Warning (dev) at cmake/localbuild/Findrpclib.cmake:31 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  examples/calculator/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Configuring done
Generating done

**Comment by sztomi** [comment]
@moguorong The warnings are something I tried to get rid of previously, but couldn't because it worked differently on AppVeyor. Anyway, the only error I see is not finding SFML. I suggest either installing it or not building the mandelbrot examples. For the warnings, I'm opening a separate issue and will reference it here.

**Comment by sztomi** [comment]
I ultimately decided against this, because it entails too many hacks for little benefit. Supporting VS2015 is reasonable enough.
