### ISSUE TITLE
Timout should be applied when waiting for connection

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#114]
@sztomi  @dkozel

```
void bug() {
  rpc::client c("localhost", port);// assume server not connected
  c.set_timeout(1000);
  // could call c.get_connection_state() to check if it's rpc::client::connection_state::connected but that's brittle and could run into bugs when it gets disconnected right after we check
  auto res = c.call("fun").as<string>(); // hangs instead of timout exception
}
```
another example is when server disconnects:

```
void bug() {
  rpc::client c("localhost", port);
  c.set_timeout(1000);
  // could call c.get_connection_state() to check if it's rpc::client::connection_state::connected but that's brittle and could run into bugs when it gets disconnected right after we check
  while(true){
    auto res = c.call("fun").as<string>(); // hangs when server disconnects instead of timout exception
   // maybe sleep  a bit here
  // assume server gets disconnected at some point
  }
}
```

EDIT: adding a check on get_connection_state doesn't even help because initally state is `initial`  
```
if(c.get_connection_state()==rpc::client::connection_state::connected){
 // won't get inside here, initially state is `initial`
  auto res = c.call("fun").as<string>();
}
```

so looks like `timeout` isnt' currently very useful; any workaround?

**Comment by sztomi** [comment]
Thanks for reporting this. The problem occurs because the client connect asynchronously and waits for the connection at the very first call. I forgot about this waiting and the timeout is not added at that point. I'm going to think about this. I'd like to avoid having a `connect` function, because part of the API philosophy of rpclib was that if you have an object, it should be useable right away. I can let go of that if I can't find a better way though :)

**Comment by sztomi** [comment]
OK, this should be a simple fix, but there is no easy workaround. It will be added here: 
https://github.com/rpclib/rpclib/blob/master/lib/rpc/client.cc#L166

**Comment by timotheecour** [comment]
@sztomi  PTAL

**Comment by sztomi** [comment]
This was released: https://github.com/rpclib/rpclib/releases/tag/v2.1.0
