### ISSUE TITLE
exception handling shows no context compared to python msgpack rpc

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#124]
@sztomi 

```
try{
     auto result = client.call("foo").as<int>();
  } catch(const std::exception& e){
    std::cout<<e.what() <<std::endl;
  }
```
prints: `rpc::rpc_error during call`

which is not informative.

in python it shows much more context, eg: a stacktrack plus a real error msg, for eg, `msgpackrpc.error.RPCError: global name 'foo' is not defined`

How would I get more information using rpclib?

**Comment by sztomi** [comment]
As the error message states, you caught a `rpc_error` object. Cast to that type (or better, catch it right away) and you will have more information. There are specific error messages about not finding a function name or invalid number of arguments passed.

Error handling is covered in the documentation: 

  * http://rpclib.net/primer/#responding-with-errors
  * http://rpclib.net/primer/#error-handling

And here are some relevant unit tests: https://github.com/rpclib/rpclib/blob/master/tests/rpc/server_test.cc#L125

As for a stack trace, C++ is not Python, so it's not as easy. It is also important to understand the difference between stack traces of client and server code. If you would like to get a server stack trace, you will need to obtain it on the server and return it as (part of) an error object. Since this is not covered by the standard, you will need to implement it in a less portable way. [This article covers libunwind](http://eli.thegreenplace.net/2015/programmatic-access-to-the-call-stack-in-c/), which is a modern and good library for this.

Client stack traces will not be terribly interesting, because they will also be an exception thrown from `client::call`.
