### ISSUE TITLE
Compiling rpclib as a part of my project

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#139]
Instead of referencing rcplib as librray, I want to include the source code of rpclib and compile it from my project itself. This is specifically needed for Unreal related projects because compiling rpclib outside of Unreal build system seems to pose problems (Unreal Build System uses its own version of clang and libc++). 

To do this, I would do as follows:
1. Add all files under rpclib/include and rpclib/dependencies/includes as header in my project.
2. Add all files under rpclib/src and rpclib/dependencies/src as source in my project.
3. Define following macros:
```
_GNU_SOURCE
ASIO_HAS_STD_ADDRESSOF
ASIO_HAS_STD_ARRAY
ASIO_HAS_CSTDINT
ASIO_HAS_STD_SHARED_PTR
ASIO_HAS_STD_TYPE_TRAITS
RPCLIB_ARCH_X64
RPCLIB_WIN32
ASIO_STANDALONE
RPCLIB_ASIO=clmdep_asio
RPCLIB_FMT=clmdep_fmt
RPCLIB_MSGPACK=clmdep_msgpack

```

Apart from this do I need to anything else? Any other settings of importance?

**Comment by sztomi** [comment]
I think that should be enough, but I haven't tried this yet. If you run into problems, do update. Closing this for now.

**Comment by sytelus** [comment]
I tried this out today and first thing I hit was that I also need to include headers in dependency folder. Now the problem is that headers in that folder are being referenced without subfolder. For example, just `#include "format.h"` which unfortunately may collide with existing headers of same name. It would be great if we can put headers in dependency inside folder so that referenced something like `#include "rpclib/deps/format.h"`. I'll made some local changes and try out if this works.

**Comment by sztomi** [comment]
I would be OK with such change. The reason that only msgpack and asio were moved under the dependencies/rpc directory was that those dependencies are visible on the interface (i.e. need to be installed) and that would potentially cause problems if there are system-installed counterparts. Others, like fmtlib are private dependencies. Those should be moved to a different directory (different than dependencies/rpc) because they need not be installed.

> Also, I think lot of things have changed since last time.

Not much in terms of the layout of the project. I did rewrite the cmake scripts but stuff was under the dependencies for a long time.
