### ISSUE TITLE
CMake: Remove useless VERSION variables

### ISSUE THREAD

**Issue by AravK** [rpclib/rpclib#150]
Instead, use `project(rpc VERSION <MAJOR>.<MINOR>.<PATCH>)` with a more recent CMake version (I use 3.8, may be too recent?)

**Comment by sztomi** [comment]
The variables are not entirely useless, they are the single source of truth for versioning. version.h is generated from those and the deploy scripts also depend on them. Is there a way to use these new-style versions in `configure_file`? Since there is already a cmake rewrite issue, I'm closing this one. Let's continue the discussion there: https://github.com/rpclib/rpclib/issues/94
