### ISSUE TITLE
Asio's namespace

### ISSUE THREAD

**Issue by NukeBird** [rpclib/rpclib#165]
Currently, I'm trying to add rpclib to [hunter package manager](https://github.com/ruslo/hunter): 
[Add rpclib to hunter-packages](https://github.com/ruslo/hunter/issues/1209)

This [pull request](https://github.com/rpclib/rpclib/commit/3a7db94a23dcf243749ea9d89353e6bade9015c7) looks not okay for me. Is namespace renaming really needed? Why we can't just write this code inside rpclib's header file (we DON'T need to modify dependencies)?:
```cpp
namespace clmdep_asio
{
	using namespace asio;
};
```

rpclib will be forked to hunter-packages, because hunter somehow must manage dependencies by itself (no need in "dependency" folder)

**Comment by sztomi** [comment]
Namespace renaming is performed because there is no such thing as a private linker symbol (at least, no standard-conforming way to do it). `rpclib` shipping dependencies means that any time an end-user links the same library, they run the risk of horrible linker (or worse, runtime) errors. By renaming the namespaces the resulting symbols are renamed as well. The tradeoff is larger binary format. 

I do want to make rpclib less dependent on the shipped dependencies by making them optional.

**Comment by NukeBird** [comment]
@sztomi maybe we can keep "asio" namespace? What "clmdep_" means? 

Without such renaming we also don't need this:
```cpp
namespace clmdep_asio
{
	using namespace asio;
};
```

On the other hand, we can also use dirty hack like `#define clmdep_asio asio` (but I don't think that clmdep_asio is really needed)

**Comment by NukeBird** [comment]
```cpp
if(Boost_FOUND)
 <use it>
else()
 <use rpclib's asio>
endif()
```

?

**Comment by sztomi** [comment]
> maybe we can keep "asio" namespace? What "clmdep_" means?

We can't, otherwise the linker symbols might collide. 

`clmdep_` is "callme dep". The library was originally called `callme`. Purely because I thought I will add a `maybe` class and that would have allowed me to write `callme::maybe` (true story, you can check the git history :)).

> Without such renaming we also don't need this:

```cpp
namespace clmdep_asio
{
	using namespace asio;
};
```

This doesn't help, and doesn't do what (I think) your intention is.

```cmake
if(Boost_FOUND)
 <use it>
else()
 <use rpclib's asio>
endif()
```

That's kind of the idea, but it is yet to be implemented.

**Comment by NukeBird** [comment]
`This doesn't help, and doesn't do what (I think) your intention is.`
Hunter has all packages that rpclib needs (gmock, gtest, asio)

BUT. Hunter will load and install original libs with its standard namespaces. So I can't delete dependencies folder and modify rpclib-fork's CMakeLists like this:
```cpp
hunter_add_package(Boost)
find_package(Boost CONFIG REQUIRED)
target_link_libraries(... Boost::boost)
```

As I mentioned before, hunter - is a package/dependency manager. So packages also must be loaded by hunter. If you are interested, you can read this: https://docs.hunter.sh/en/latest/creating-new.html

`That's kind of the idea, but it is yet to be implemented.`
 I can try to do it

**Comment by NukeBird** [comment]
Oh! I notice RPCLIB_ASIO definition! 

It makes everything much easier ^^

https://github.com/rpclib/rpclib/blob/3b00c4ccf480b9f9569b1d064e7a3b43585b8dfd/CMakeLists.txt#L148

**Comment by sztomi** [comment]
But can't you package it without using the hunter-provided deps? rpclib in its current state *is* self-contained.

**Comment by NukeBird** [comment]
It is possible but not recommended

**Comment by sztomi** [comment]
Closing this in favor of #155 , let's move any further discussion there.
