### ISSUE TITLE
Pthread symbols exposed in librpc

### ISSUE THREAD

**Issue by wouter-heerwegh** [rpclib/rpclib#316]
Hi,

I've recently had some issues trying to use librpc in our custom version of Airsim. Mainly because pthread symbols are exposed in the librpc.a library.

When this library is then used in unreal engine (which uses a cross compile toolchain to build), errors are thrown, because the cross compile toolchain uses a different glibc version than my native system and it finds an undefined symbol (`pthread_cond_clockwait`).

I'm a noob when it comes to compilation and linking. Does anyone have an idea if it possible to not expose the pthread symbols in librpc? If not, is it really necessary for a static library to expose symbols of it's dependencies?

**Comment by ahtilego** [comment]
It seems that you have some misconceptions about static libraries and linking. Your problem seems to be either not linking in pthread into your binary (missing -lpthread on linker command line), or mismatching glibc versions. That is librpc is compiled, depending on one version of glibc, and you're linking your binary, using a different version. This mismatch can happen for example when you're using newer compiler to build librpc than you're using to build the application.

**Comment by wouter-heerwegh** [comment]
Yeah indeed. I guess I will have to build it in a docker container or something that has an older version of glibc, and then use that on a newer system, since it is supposed to be backwards compatible. Thanks for the response.
