### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by sztomi** [rpclib/rpclib#33]
The initial implementation uses very few C++14 features, so it makes sense to try and broaden the compiler support. C++11 is pretty well-supported today.

**Comment by sytelus** [comment]
This would be super useful. Lot of build systems such as ROS, Unreal etc are still on C++11 and it makes it very hard to use this wonderful library. It would be nice to turn off certain features so that they are not available for C++11 but basic core features can be made available for C++11 as well.

**Comment by sztomi** [comment]
#107 was merged!
