### ISSUE TITLE
is RPCLIB_MSGPACK = clmdep_msgpack::v1?

### ISSUE THREAD

**Issue by ranbochen** [rpclib/rpclib#88]
there is no such namespace defined in source code
use /D "RPCLIB_MSGPACK=clmdep_msgpack::v1" to comple?
is it?

**Comment by sztomi** [comment]
It's just `clmdep_msgpack`. This is already fixed on the dev branch in cmake (it provides the necessary flags in a variable, e.g. here: https://github.com/rpclib/rpclib/blob/master/examples/calculator/CMakeLists.txt#L15). Maybe this define should also be added to some sort of config.h file. The idea here is that the namespaces of dependencies are renamed so that any collision with existing and installed dependencies is avoided in the same program. In the future, it is possible that I'll move all dependencies to conan.

**Comment by ranbochen** [comment]
thanks for answer.
