### ISSUE TITLE
Large number of header files in include

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#93]
There are 496 header files in include/rpc amounting to over 5MB of code. Are all of these required to use the library? It would be great if there is any way to hide/minimize these large number of headers in order to use the library.

**Comment by sztomi** [comment]
Fair enough, I never measured this and it does sound excessive. I will try to come up with something to remove unneeded stuff. I'm sure not all of them are needed, although I suspect that a large chunk is asio which has platform-specific implementations for various functionality.

**Comment by sztomi** [comment]
So, I looked at this in detail. The vast majority of the headers come from the bundled msgpack. It's largely a black box for me, but I do think they need most of the headers. I could implement an amalgamation script, but it's risky and I don't see that much value in decreasing the number of headers. This is a compromise that comes from bundling the dependencies. Unfortunately msgpack needs to be visible on the interface due to the templates. I could remove msgpack from the repo, but then installation would become painful without decreasing the final number of required headers (and users installing different msgpack versions and reporting issues with them would be a nightmare). I thought about implementing a msgpack parser and encoder in rpclib, but the canonical implementation is very high quality and optimized to hell. I'd have no chance of reaching its performance. I wouldn't say "never", but not in the forseeable future, unfortunately. If there is a more compact msgpack release, I'll certainly update to it.
