### ISSUE TITLE
server() should avoid asking parameters until its run

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#95]
Currently server class has no default constructor. This creates a problem if you want to use it as local variable and RAII pattern but don't have port number or other details available yet. Also server doesn't really need all these information until its run(). Ideally, we should avoid asking for parameters until its needed. So perhaps a better design is to have overload for run() that takes necessary parameters and add a default constructor for server object.

**Comment by sztomi** [comment]
Good idea. I'm planning a larger refactor post-1.0.0 with interface breaking changes and I will consider this. For 1.0.0 I won't do this change however. (BTW 1.0.0 is basically finished, but I'm holding off until I finish the benchmark suite and comparisons).

**Comment by sztomi** [comment]
I've experimented a lot with this, but so far I could not find a good enough setup from an API design standpoint. The issue is that setting the port in the run call seems really unnatural to me (plus it's contrary to the asio design, which rpclib tries to mimic somewhat). Providing a default parameter and resetting the pimpl if a setter is called is weird and increases the learning curve. 

To address your original problem, RAII can be used if the client code uses a unique_ptr to store the server and only creates it when it's needed. It's a minor performance hit because of the heap allocation and indirection, but with RPC in general that shouldn't be an issue. 

I will keep this issue in mind when I get to the policy-based refactoring, but for now I have to set it aside.
