### ISSUE TITLE
Preprocessor definations required for library user project

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#96]
I'm dropping rpc.lib and include files in a separate VC++ project as dependency and trying to use it in that project. I got the compile error that symbol RPCLIB_MSGPACK was not defined. After some debugging I found that CMakeLists.txt inserts huge number of preprocessor symbols for VC++ projects as shown below. So I copied value for RPCLIB_MSGPACK from there and then compilation was successful. So this is what I needed to do:

```
#define RPCLIB_MSGPACK clmdep_msgpack
#include "rpc/server.h"
```

Is this a bug? 

I'm also wondering if I need any other preprocessor definitions from CMakeLists.txt. It would be great if there is no need to define any preprocessor symbols in the host project.

```
WIN32
WINDOWS
WIN32_LEAN_AND_MEAN
NOMINMAX
VC_EXTRALEAN
CRT_SECURE_NO_WARNINGS
CRT_NONSTDC_NO_DEPRECATE
WIN32_WINNT=0x0501
GNU_SOURCE
ASIO_HAS_STD_ADDRESSOF
ASIO_HAS_STD_ARRAY
ASIO_HAS_CSTDINT
ASIO_HAS_STD_SHARED_PTR
ASIO_HAS_STD_TYPE_TRAITS
RPCLIB_ARCH_X64
RPCLIB_WIN32
ASIO_STANDALONE
RPCLIB_ASIO=clmdep_asio
RPCLIB_FMT=clmdep_fmt
**RPCLIB_MSGPACK=clmdep_msgpack**
CMAKE_INTDIR="Debug"
```

**Comment by sztomi** [comment]
Well, Findrpclib.cmake does this for you, but I wasn't knowledgeable enough about cmake when I started this project. So the intended way to integrate the library is to use find_module.
I will need to make sure that the library is usable as a submodule since it's something that many people seem to prefer. Also, not everyone uses cmake, and your use-case of simply copying the headers is perfectly valid as well.

The basic idea here is that all dependencies are shipped with rpclib, but hidden (renamed) in a namespace. This allows user code to use the same libraries and still avoid linker errors. The only dependency which is visible on the interface is msgpack (it has to be for all the bind-stuff and serialization). That is why this define is needed.

Anyway, this is definitely something that will be done before 1.0.0. BTW, if you are using the library now, I suggest using master (instead of 1.0.0-pre) because buffer overflow bugs were found and fixed since then.

**Comment by sytelus** [comment]
Thanks for taking care of this. BTW, you might be happy to know that we are using rpclib in AirSim project we released couple of days ago (we have been trending in GitHub top 5 projects for past couple of days :)): 

https://github.com/microsoft/airsim

rpclib is an excellent library. Hope to see more in near future.

**Comment by sztomi** [comment]
Wow, thanks! I sure am happy to hear that. Also, it's nice to see context for the other issues reported. 1.0.0 is coming soon, along with a nice benchmark suite. I'm dragging on the release because as I implement the benchmarks, I constantly find things to improve.

**Comment by sztomi** [comment]
I've verified that the current dev branch does not have this issue due to having the macro defined in the new `config.h` header. I'll close this issue when it's merged to master.

**Comment by sztomi** [comment]
1.0.0 has been released and the fix was merged to master.
